The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /home/jeongseokoh/.cache/huggingface/token
Login successful
INFO 08-06 19:04:34 llm_engine.py:161] Initializing an LLM engine (v0.5.0.post1) with config: model='meta-llama/Meta-Llama-3-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Meta-Llama-3-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir='../../hub/model/', load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=meta-llama/Meta-Llama-3-8B-Instruct)
INFO 08-06 19:04:38 weight_utils.py:218] Using model weights format ['*.safetensors']
INFO 08-06 19:04:43 model_runner.py:160] Loading model weights took 14.9595 GB
INFO 08-06 19:04:44 gpu_executor.py:83] # GPU blocks: 13407, # CPU blocks: 2048
INFO 08-06 19:04:48 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 08-06 19:04:48 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 08-06 19:05:00 model_runner.py:965] Graph capturing finished in 12 secs.
Model: llama3_8b is selected
Dataset: gsm8k is selected
Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.35s/it, est. speed input: 213.58 toks/s, output: 291.74 toks/s]Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.35s/it, est. speed input: 213.58 toks/s, output: 291.74 toks/s]
Second job: 4.359029897022992 sec
Processed prompts:   0%|          | 0/5 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]Processed prompts:  20%|██        | 1/5 [00:00<00:03,  1.33it/s, est. speed input: 1409.52 toks/s, output: 10.62 toks/s]Processed prompts: 100%|██████████| 5/5 [00:00<00:00,  6.63it/s, est. speed input: 7009.32 toks/s, output: 53.06 toks/s]
Last job: 0.7734288569772616 sec
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data2/jeongseokoh/jeongseokoh/inter_SC/inter_SC.py", line 828, in <module>
[rank0]:     main()
[rank0]:   File "/data2/jeongseokoh/jeongseokoh/inter_SC/inter_SC.py", line 813, in main
[rank0]:     results = parallel_process(context=c_dataset, question=q_dataset, answer=a_dataset, option=o_dataset, cot_ex=cot_ex, model=model, model_name=selected_model, dataset=selected_dataset)
[rank0]:   File "/data2/jeongseokoh/jeongseokoh/inter_SC/inter_SC.py", line 442, in parallel_process
[rank0]:     original_answer_completion = get_completion(context=c, question=q, choices=o, cot_ex=cot_ex, model=model, model_name=model_name, dataset=dataset)
[rank0]:   File "/data2/jeongseokoh/jeongseokoh/inter_SC/inter_SC.py", line 273, in get_completion
[rank0]:     completion2.append(get_added_prompt(new_conversations[i], j))
[rank0]: IndexError: list index out of range
srun: error: n02: task 0: Exited with exit code 1
